
//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SnmpClient
{

using System;
    using System.Collections.Generic;
    
public partial class OID
{

    public string Vendor { get; set; }

    public string Dato { get; set; }

    public string NumeroOID { get; set; }

}

}
