//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnmpClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class OIDRicoh
    {
        public string Uptime { get; set; }
        public string Nome { get; set; }
        public string Stampe { get; set; }
        public string MAC { get; set; }
        public string Yellow { get; set; }
        public string Magenta { get; set; }
        public string Ciano { get; set; }
        public string Black { get; set; }
    }
}
