//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnmpClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class OIDStampanti
    {
        public string OID { get; set; }
        public string Marca { get; set; }
    }
}
