//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnmpClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stampanti
    {
        public int IDStampante { get; set; }
        public string Nome { get; set; }
        public string IP { get; set; }
        public int NumeroStampe { get; set; }
        public System.DateTime Data { get; set; }
    }
}
