
//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SnmpClient
{

using System;
    using System.Collections.Generic;
    
public partial class ValoriStampanti
{

    public int IDValore { get; set; }

    public int IDDiscovery { get; set; }

    public string TipoDato { get; set; }

    public string Valore { get; set; }

    public System.DateTime Data { get; set; }



    public virtual Discovery Discovery { get; set; }

}

}
